In [5]:
from vivarium import Artifact
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from db_queries import get_ids, get_outputs
import scipy.stats

!whoami
!date

alibow
Thu Jun 18 15:50:09 PDT 2020

In [6]:
output_dirs = ['/share/costeffectiveness/results/vivarium_conic_lsff/00_bugfix/v7.0_prelim_nigeria/count_data/']

locations = ['Nigeria']

In [7]:
# available data frames

# births
# births_with_ntd
# birth_weight
# deaths
# gestational_age
# person_time
# population
# state_person_time
# transition_count
# ylds
# ylls

In [8]:
bw = pd.read_hdf(output_dirs[0] + 'birth_weight.hdf')
bw.head()

,measure,input_draw,scenario,value
0,birth_weight_mean_in_2020_among_female_iron_fo...,357,baseline,3244.991958
1,birth_weight_mean_in_2020_among_female_iron_fo...,357,folic_acid_fortification_scale_up,3244.991958
2,birth_weight_mean_in_2020_among_female_iron_fo...,357,iron_fortification_scale_up,3244.991958
3,birth_weight_mean_in_2020_among_female_iron_fo...,357,vitamin_a_fortification_scale_up,3244.991958
4,birth_weight_mean_in_2020_among_female_iron_fo...,602,baseline,3111.953987

In [9]:
np.unique(bw['measure'])

array(['birth_weight_mean_in_2020_among_female_iron_fortification_group_covered',
       'birth_weight_mean_in_2020_among_female_iron_fortification_group_uncovered',
       'birth_weight_mean_in_2020_among_male_iron_fortification_group_covered',
       'birth_weight_mean_in_2020_among_male_iron_fortification_group_uncovered',
       'birth_weight_mean_in_2021_among_female_iron_fortification_group_covered',
       'birth_weight_mean_in_2021_among_female_iron_fortification_group_uncovered',
       'birth_weight_mean_in_2021_among_male_iron_fortification_group_covered',
       'birth_weight_mean_in_2021_among_male_iron_fortification_group_uncovered',
       'birth_weight_mean_in_2022_among_female_iron_fortification_group_covered',
       'birth_weight_mean_in_2022_among_female_iron_fortification_group_uncovered',
       'birth_weight_mean_in_2022_among_male_iron_fortification_group_covered',
       'birth_weight_mean_in_2022_among_male_iron_fortification_group_uncovered',
       'birth_weight_mean_in_2023_among_female_iron_fortification_group_covered',
       'birth_weight_mean_in_2023_among_female_iron_fortification_group_uncovered',
       'birth_weight_mean_in_2023_among_male_iron_fortification_group_covered',
       'birth_weight_mean_in_2023_among_male_iron_fortification_group_uncovered',
       'birth_weight_mean_in_2024_among_female_iron_fortification_group_covered',
       'birth_weight_mean_in_2024_among_female_iron_fortification_group_uncovered',
       'birth_weight_mean_in_2024_among_male_iron_fortification_group_covered',
       'birth_weight_mean_in_2024_among_male_iron_fortification_group_uncovered',
       'birth_weight_mean_in_2025_among_female_iron_fortification_group_covered',
       'birth_weight_mean_in_2025_among_female_iron_fortification_group_uncovered',
       'birth_weight_mean_in_2025_among_male_iron_fortification_group_covered',
       'birth_weight_mean_in_2025_among_male_iron_fortification_group_uncovered',
       'birth_weight_sd_in_2020_among_female_iron_fortification_group_covered',
       'birth_weight_sd_in_2020_among_female_iron_fortification_group_uncovered',
       'birth_weight_sd_in_2020_among_male_iron_fortification_group_covered',
       'birth_weight_sd_in_2020_among_male_iron_fortification_group_uncovered',
       'birth_weight_sd_in_2021_among_female_iron_fortification_group_covered',
       'birth_weight_sd_in_2021_among_female_iron_fortification_group_uncovered',
       'birth_weight_sd_in_2021_among_male_iron_fortification_group_covered',
       'birth_weight_sd_in_2021_among_male_iron_fortification_group_uncovered',
       'birth_weight_sd_in_2022_among_female_iron_fortification_group_covered',
       'birth_weight_sd_in_2022_among_female_iron_fortification_group_uncovered',
       'birth_weight_sd_in_2022_among_male_iron_fortification_group_covered',
       'birth_weight_sd_in_2022_among_male_iron_fortification_group_uncovered',
       'birth_weight_sd_in_2023_among_female_iron_fortification_group_covered',
       'birth_weight_sd_in_2023_among_female_iron_fortification_group_uncovered',
       'birth_weight_sd_in_2023_among_male_iron_fortification_group_covered',
       'birth_weight_sd_in_2023_among_male_iron_fortification_group_uncovered',
       'birth_weight_sd_in_2024_among_female_iron_fortification_group_covered',
       'birth_weight_sd_in_2024_among_female_iron_fortification_group_uncovered',
       'birth_weight_sd_in_2024_among_male_iron_fortification_group_covered',
       'birth_weight_sd_in_2024_among_male_iron_fortification_group_uncovered',
       'birth_weight_sd_in_2025_among_female_iron_fortification_group_covered',
       'birth_weight_sd_in_2025_among_female_iron_fortification_group_uncovered',
       'birth_weight_sd_in_2025_among_male_iron_fortification_group_covered',
       'birth_weight_sd_in_2025_among_male_iron_fortification_group_uncovered'],
      dtype=object)

In [11]:
bw_mean = bw.groupby(['scenario']).describe()
bw_mean['value']

# NOTE... this line of code incorrectly averages values over both standard deviation and mean measures of bw
# still, we can see that there are no differences in birth weight measures across scenarios
# there should be differences in the iron fortification scenario

,count,mean,std,min,25%,50%,75%,max
scenario,,,,,,,,
baseline,96.0,1894.878316,1273.944085,485.747026,630.977923,1873.323999,3139.673945,3263.109826
folic_acid_fortification_scale_up,96.0,1894.878316,1273.944085,485.747026,630.977923,1873.323999,3139.673945,3263.109826
iron_fortification_scale_up,96.0,1894.878316,1273.944085,485.747026,630.977923,1873.323999,3139.673945,3263.109826
vitamin_a_fortification_scale_up,96.0,1894.878316,1273.944085,485.747026,630.977923,1873.323999,3139.673945,3263.109826

In [7]:
# mean birth weight should be identical between these three scenarios
    # issue with common random numbers?

In [13]:
ga = pd.read_hdf(output_dirs[0] + 'gestational_age.hdf')
ga.head()

,measure,input_draw,scenario,value
0,gestational_age_mean,357,baseline,38.705731
1,gestational_age_mean,357,folic_acid_fortification_scale_up,38.705731
2,gestational_age_mean,357,iron_fortification_scale_up,38.705731
3,gestational_age_mean,357,vitamin_a_fortification_scale_up,38.705731
4,gestational_age_mean,602,baseline,38.318606

In [14]:
np.unique(ga['measure'])

array(['gestational_age_mean', 'gestational_age_sd'], dtype=object)

In [15]:
ga_mean = ga.groupby(['measure','scenario']).describe()
ga_mean

                                                       input_draw         \
                                                            count   mean
measure              scenario
gestational_age_mean baseline                                 2.0  479.5
                     folic_acid_fortification_scale_up        2.0  479.5
                     iron_fortification_scale_up              2.0  479.5
                     vitamin_a_fortification_scale_up         2.0  479.5
gestational_age_sd   baseline                                 2.0  479.5
                     folic_acid_fortification_scale_up        2.0  479.5
                     iron_fortification_scale_up              2.0  479.5
                     vitamin_a_fortification_scale_up         2.0  479.5

                                                                           \
                                                               std    min
measure              scenario
gestational_age_mean baseline                           173.241161  357.0
                     folic_acid_fortification_scale_up  173.241161  357.0
                     iron_fortification_scale_up        173.241161  357.0
                     vitamin_a_fortification_scale_up   173.241161  357.0
gestational_age_sd   baseline                           173.241161  357.0
                     folic_acid_fortification_scale_up  173.241161  357.0
                     iron_fortification_scale_up        173.241161  357.0
                     vitamin_a_fortification_scale_up   173.241161  357.0

                                                                               \
                                                           25%    50%     75%
measure              scenario
gestational_age_mean baseline                           418.25  479.5  540.75
                     folic_acid_fortification_scale_up  418.25  479.5  540.75
                     iron_fortification_scale_up        418.25  479.5  540.75
                     vitamin_a_fortification_scale_up   418.25  479.5  540.75
gestational_age_sd   baseline                           418.25  479.5  540.75
                     folic_acid_fortification_scale_up  418.25  479.5  540.75
                     iron_fortification_scale_up        418.25  479.5  540.75
                     vitamin_a_fortification_scale_up   418.25  479.5  540.75

                                                              value  \
                                                          max count
measure              scenario
gestational_age_mean baseline                           602.0   2.0
                     folic_acid_fortification_scale_up  602.0   2.0
                     iron_fortification_scale_up        602.0   2.0
                     vitamin_a_fortification_scale_up   602.0   2.0
gestational_age_sd   baseline                           602.0   2.0
                     folic_acid_fortification_scale_up  602.0   2.0
                     iron_fortification_scale_up        602.0   2.0
                     vitamin_a_fortification_scale_up   602.0   2.0

                                                                             \
                                                             mean       std
measure              scenario
gestational_age_mean baseline                           38.512168  0.273738
                     folic_acid_fortification_scale_up  38.512168  0.273738
                     iron_fortification_scale_up        38.512168  0.273738
                     vitamin_a_fortification_scale_up   38.512168  0.273738
gestational_age_sd   baseline                            2.252619  1.421868
                     folic_acid_fortification_scale_up   2.252619  1.421868
                     iron_fortification_scale_up         2.252619  1.421868
                     vitamin_a_fortification_scale_up    2.252619  1.421868

                                                                              \
                                                              min        25%
measure              scenario
gestational_age_mean baseline                           38.318606  38.415387
                     folic_acid_fortification_scale_up  38.318606  38.415387
                     iron_fortification_scale_up        38.318606  38.415387
                     vitamin_a_fortification_scale_up   38.318606  38.415387
gestational_age_sd   baseline                            1.247207   1.749913
                     folic_acid_fortification_scale_up   1.247207   1.749913
                     iron_fortification_scale_up         1.247207   1.749913
                     vitamin_a_fortification_scale_up    1.247207   1.749913

                                                                              \
                                                              50%        75%
measure              scenario
gestational_age_mean baseline                           38.512168  38.608949
                     folic_acid_fortification_scale_up  38.512168  38.608949
                     iron_fortification_scale_up        38.512168  38.608949
                     vitamin_a_fortification_scale_up   38.512168  38.608949
gestational_age_sd   baseline                            2.252619   2.755326
                     folic_acid_fortification_scale_up   2.252619   2.755326
                     iron_fortification_scale_up         2.252619   2.755326
                     vitamin_a_fortification_scale_up    2.252619   2.755326


                                                              max
measure              scenario
gestational_age_mean baseline                           38.705731
                     folic_acid_fortification_scale_up  38.705731
                     iron_fortification_scale_up        38.705731
                     vitamin_a_fortification_scale_up   38.705731
gestational_age_sd   baseline                            3.258032
                     folic_acid_fortification_scale_up   3.258032
                     iron_fortification_scale_up         3.258032
                     vitamin_a_fortification_scale_up    3.258032

In [11]:
births = pd.read_hdf(output_dirs[0] + 'births.hdf')
births.head()

,year,sex,folic_acid_fortification_group,measure,input_draw,scenario,value
0,2020,female,covered,live_births,357,baseline,76.0
1,2020,female,covered,live_births,357,baseline,0.0
2,2020,female,covered,live_births,357,baseline,11.0
3,2020,female,covered,live_births,357,folic_acid_fortification_scale_up,76.0
4,2020,female,covered,live_births,357,folic_acid_fortification_scale_up,0.0

In [12]:
np.unique(births['measure'])

array(['live_births'], dtype=object)

In [13]:
births_mean = births.groupby(['input_draw','scenario']).sum().groupby(['scenario']).mean()
births_mean

                                     value
scenario
baseline                           22489.5
folic_acid_fortification_scale_up  22489.5
iron_fortification_scale_up        22489.5
vitamin_a_fortification_scale_up   22489.5

# Conclusions

- Number of live births is consistent between scenarios, which is good!
- The count space conversion for birth weight measures did not seem to occur as expected (this is also different than how the gestational age is reported, which has no stratification)
- The mean birth weight did not appear to differ for the iron fortification scenario - it should for this scenario only
- The mean gestational age did not differ between scenarios, as expected