In [3]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt
import gbd_mapping as gbd
# from db_queries import get_outputs, get_ids
# from get_draws.api import get_draws
from vivarium import Artifact

import os

!whoami
!date

ndbs
Thu Feb  6 15:57:23 PST 2020

In [4]:
base_dir = '/share/costeffectiveness/results/vivarium_gates_bep/malnutrition'

locations_rundates = {
    'India': '2020_02_05_03_02_13',
#     'Pakistan': ''
    'Mali': '2020_02_05_03_02_02',
    'Tanzania': '2020_02_05_03_07_37',
}

In [71]:
def load_transformed_count_data(directory):
    """
    Loads each transformed "count space" .hdf output file into a dataframe,
    and returns a dictionary whose keys are the file names and values are
    are the corresponding dataframes.
    """
    dfs = {}
    for entry in os.scandir(directory):
        filename_root, extension = os.path.splitext(entry.name)
        if extension == '.hdf':
#             print(filename_root, type(filename_root), extension, entry.path)
            dfs[filename_root] = pd.read_hdf(entry.path)
    return dfs

def path_for_transformed_count_data(directory, location, rundate):
    """
    Gets the directory path for a given location and rundate.
    
    The returned path is 
    f'{directory}/{location.lower()}/{rundate}/count_space'
    """
    return os.path.join(directory, location.lower(), rundate, 'count_space')

def load_all_data(directory, locations_rundates):
    """
    Loads data from all locations into a dictionary of dataframes,
    indexed by (location, filename).
    
    Assumes data files are in a directory called
    f'{directory}/{location.lower()}/{rundate}/{subdirectory}/'
    """
    dfs = {}
    for location in locations_rundates:
        path = path_for_transformed_count_data(directory, location, locations_rundates[location])
        location_dfs = load_transformed_count_data(path)
        
        for key in location_dfs:
            dfs[(location.lower(), key)] = location_dfs[key]
            
    return dfs

In [72]:
#mali = load_transformed_count_data(base_dir, 'Mali', '2020_02_05_03_02_02')
raw_data = load_all_data(base_dir, locations_rundates)
list(raw_data.keys())

[('india', 'birth_prevalence'),
 ('india', 'transition_count'),
 ('india', 'deaths'),
 ('india', 'state_person_time'),
 ('india', 'population'),
 ('india', 'person_time'),
 ('india', 'category_counts'),
 ('india', 'single_columns'),
 ('india', 'ylls'),
 ('india', 'ylds'),
 ('mali', 'birth_prevalence'),
 ('mali', 'transition_count'),
 ('mali', 'deaths'),
 ('mali', 'state_person_time'),
 ('mali', 'population'),
 ('mali', 'person_time'),
 ('mali', 'category_counts'),
 ('mali', 'single_columns'),
 ('mali', 'ylls'),
 ('mali', 'ylds'),
 ('tanzania', 'birth_prevalence'),
 ('tanzania', 'transition_count'),
 ('tanzania', 'deaths'),
 ('tanzania', 'state_person_time'),
 ('tanzania', 'population'),
 ('tanzania', 'person_time'),
 ('tanzania', 'category_counts'),
 ('tanzania', 'single_columns'),
 ('tanzania', 'ylls'),
 ('tanzania', 'ylds')]

In [73]:
print(raw_data[('mali', 'single_columns')].shape) #10*3
raw_data[('mali', 'single_columns')]

(30, 1)

                                                count
input_draw property
29.0       total_population             100000.000000
           years_of_life_lost           584310.792236
           years_lived_with_disability    1371.105022
232.0      total_population             100000.000000
           years_of_life_lost           601337.363841
           years_lived_with_disability    1313.744345
357.0      total_population             100000.000000
           years_of_life_lost           579065.795415
           years_lived_with_disability    1689.362760
394.0      total_population             100000.000000
           years_of_life_lost           644276.446911
           years_lived_with_disability    1142.013617
602.0      total_population             100000.000000
           years_of_life_lost           594017.162661
           years_lived_with_disability    1365.106154
629.0      total_population             100000.000000
           years_of_life_lost           600167.527088
           years_lived_with_disability    1374.660119
650.0      total_population             100000.000000
           years_of_life_lost           572442.810499
           years_lived_with_disability    1716.879954
680.0      total_population             100000.000000
           years_of_life_lost           464244.226531
           years_lived_with_disability    1538.913979
829.0      total_population             100000.000000
           years_of_life_lost           571406.810559
           years_lived_with_disability    1638.774893
946.0      total_population             100000.000000
           years_of_life_lost           528582.426074
           years_lived_with_disability    1108.043256

In [74]:
print(raw_data[('mali', 'birth_prevalence')].shape) # 10*1*2*2
raw_data[('mali', 'birth_prevalence')]

(40, 1)

                                                              birth_prevalence
input_draw birth_state        sex    malnourishment_category
29.0       neonatal_disorders male   malnourished                        803.0
                                     not_malnourished                   7887.0
                              female malnourished                        824.0
                                     not_malnourished                   7919.0
232.0      neonatal_disorders male   malnourished                        819.0
                                     not_malnourished                   7280.0
                              female malnourished                        758.0
                                     not_malnourished                   6884.0
357.0      neonatal_disorders male   malnourished                        795.0
                                     not_malnourished                   7713.0
                              female malnourished                        691.0
                                     not_malnourished                   6985.0
394.0      neonatal_disorders male   malnourished                        921.0
                                     not_malnourished                   8401.0
                              female malnourished                        845.0
                                     not_malnourished                   7247.0
602.0      neonatal_disorders male   malnourished                       1047.0
                                     not_malnourished                   7936.0
                              female malnourished                       1026.0
                                     not_malnourished                   7668.0
629.0      neonatal_disorders male   malnourished                        802.0
                                     not_malnourished                   7251.0
                              female malnourished                        822.0
                                     not_malnourished                   7142.0
650.0      neonatal_disorders male   malnourished                        929.0
                                     not_malnourished                   7898.0
                              female malnourished                        830.0
                                     not_malnourished                   7075.0
680.0      neonatal_disorders male   malnourished                        871.0
                                     not_malnourished                   7699.0
                              female malnourished                        817.0
                                     not_malnourished                   7162.0
829.0      neonatal_disorders male   malnourished                        881.0
                                     not_malnourished                   7678.0
                              female malnourished                        903.0
                                     not_malnourished                   7687.0
946.0      neonatal_disorders male   malnourished                       1049.0
                                     not_malnourished                   8677.0
                              female malnourished                        850.0
                                     not_malnourished                   7680.0

In [61]:
print(raw_data[('mali', 'person_time')].shape) # (10 draws)*(3 years)*(2 sexes)*(5 age_groups)*(2 malnourishment)
raw_data[('mali', 'person_time')].head(10)

(600, 1)

                                                              person_time
input_draw year sex  age_group      malnourishment_category
29.0       2020 male early_neonatal malnourished                90.499769
                                    not_malnourished           882.820467
                     late_neonatal  malnourished               264.953704
                                    not_malnourished          2616.864015
                     1mo_to_6mo     malnourished              1916.260080
                                    not_malnourished         19070.182733
                     6mo_to_1       malnourished                 4.319302
                                    not_malnourished            44.566735
                     1_to_4         malnourished                 0.000000
                                    not_malnourished             0.000000

In [63]:
raw_data[('mali', 'person_time')].index.get_level_values('year').unique()

Index(['2020', '2021', '2022'], dtype='object', name='year')

In [75]:
print(raw_data[('mali', 'state_person_time')].shape)
raw_data[('mali', 'state_person_time')].head(40)

(5400, 1)

                                                                                                         state_person_time
input_draw state                                       year sex  age_group      malnourishment_category
29.0       susceptible_to_diarrheal_diseases           2020 male early_neonatal malnourished                    100.854209
                                                                                not_malnourished                981.968515
           diarrheal_diseases                          2020 male early_neonatal malnourished                      2.872005
                                                                                not_malnourished                 27.649555
           susceptible_to_measles                      2020 male early_neonatal malnourished                    103.726215
                                                                                not_malnourished               1009.618070
           measles                                     2020 male early_neonatal malnourished                      0.000000
                                                                                not_malnourished                  0.000000
           recovered_from_measles                      2020 male early_neonatal malnourished                      0.000000
                                                                                not_malnourished                  0.000000
           susceptible_to_lower_respiratory_infections 2020 male early_neonatal malnourished                    103.370294
                                                                                not_malnourished               1004.487337
           lower_respiratory_infections                2020 male early_neonatal malnourished                      0.355921
                                                                                not_malnourished                  5.130732
           susceptible_to_meningitis                   2020 male early_neonatal malnourished                    103.630390
                                                                                not_malnourished               1008.585900
           meningitis                                  2020 male early_neonatal malnourished                      0.095825
                                                                                not_malnourished                  1.032170
           susceptible_to_diarrheal_diseases           2020 male late_neonatal  malnourished                    255.249829
                                                                                not_malnourished               2516.739220
           diarrheal_diseases                          2020 male late_neonatal  malnourished                      9.524983
                                                                                not_malnourished                 98.351814
           susceptible_to_measles                      2020 male late_neonatal  malnourished                    264.774812
                                                                                not_malnourished               2615.091034
           measles                                     2020 male late_neonatal  malnourished                      0.000000
                                                                                not_malnourished                  0.000000
           recovered_from_measles                      2020 male late_neonatal  malnourished                      0.000000
                                                                                not_malnourished                  0.000000
           susceptible_to_lower_respiratory_infections 2020 male late_neonatal  malnourished                    264.454483
                                                                                not_malnourished               2610.767967
           lower_respiratory_infections                2020 male late_neonatal  malnourished                      0.320329
                                                                                not_malnourished                  4.323066
           susceptible_to_meningitis                   2020 male late_neonatal  malnourished                    264.177960
                                                                                not_malnourished               2609.401780
           meningitis                                  2020 male late_neonatal  malnourished                      0.596851
                                                                                not_malnourished                  5.689254
           susceptible_to_diarrheal_diseases           2020 male 1mo_to_6mo     malnourished                   1712.205339
                                                                                not_malnourished              18520.120465
           diarrheal_diseases                          2020 male 1mo_to_6mo     malnourished                    197.095140
                                                                                not_malnourished                478.151951

In [78]:
raw_data[('mali', 'state_person_time')].index.get_level_values('state').unique() # 9 states

Index(['susceptible_to_diarrheal_diseases', 'diarrheal_diseases',
       'susceptible_to_measles', 'measles', 'recovered_from_measles',
       'susceptible_to_lower_respiratory_infections',
       'lower_respiratory_infections', 'susceptible_to_meningitis',
       'meningitis'],
      dtype='object', name='state')

In [79]:
10*9*3*2*5*2

5400

In [52]:
raw_data[('mali', 'category_counts')].head(20)

                                                                  category_counts
input_draw cgf_risk risk_category sex    malnourishment_category
29.0       wasting  cat1          male   malnourished                      1020.0
                                         not_malnourished                  1348.0
                    cat2          male   malnourished                      1853.0
                                         not_malnourished                  4703.0
                    cat3          male   malnourished                      2843.0
                                         not_malnourished                 14518.0
                    cat4          male   malnourished                      3003.0
                                         not_malnourished                 66941.0
           stunting cat1          male   malnourished                      1155.0
                                         not_malnourished                  1940.0
                    cat2          male   malnourished                      1660.0
                                         not_malnourished                  5326.0
                    cat3          male   malnourished                      2502.0
                                         not_malnourished                 14072.0
                    cat4          male   malnourished                      3402.0
                                         not_malnourished                 66172.0
           wasting  cat1          female malnourished                      1020.0
                                         not_malnourished                  1348.0
                    cat2          female malnourished                      1853.0
                                         not_malnourished                  4703.0

In [53]:
raw_data[('mali', 'category_counts')].shape

(320, 1)

In [54]:
raw_data[('mali', 'category_counts')].index.get_level_values('cgf_risk').unique()

Index(['wasting', 'stunting'], dtype='object', name='cgf_risk')

In [56]:
# 320 = (10 draws) * (2 risks) * (4 categories) * (2 sexes) * (2 malnourishment categories)
10*2*4*2*2

320

In [65]:
print(raw_data[('mali', 'population')].shape)
raw_data[('mali', 'population')]

(40, 1)

                      population
input_draw pop_state
29.0       living        93315.0
           dead           6685.0
           tracked      100000.0
           untracked         0.0
232.0      living        93118.0
           dead           6882.0
           tracked      100000.0
           untracked         0.0
357.0      living        93372.0
           dead           6628.0
           tracked      100000.0
           untracked         0.0
394.0      living        92628.0
           dead           7372.0
           tracked      100000.0
           untracked         0.0
602.0      living        93204.0
           dead           6796.0
           tracked      100000.0
           untracked         0.0
629.0      living        93132.0
           dead           6868.0
           tracked      100000.0
           untracked         0.0
650.0      living        93451.0
           dead           6549.0
           tracked      100000.0
           untracked         0.0
680.0      living        94688.0
           dead           5312.0
           tracked      100000.0
           untracked         0.0
829.0      living        93461.0
           dead           6539.0
           tracked      100000.0
           untracked         0.0
946.0      living        93952.0
           dead           6048.0
           tracked      100000.0
           untracked         0.0

In [66]:
print(raw_data[('mali', 'transition_count')].shape)
raw_data[('mali', 'transition_count')].head(20)

(4800, 1)

                                                                                                                transition_count
input_draw transition                                         year sex  age_group      malnourishment_category
29.0       susceptible_to_diarrheal_diseases_to_diarrheal_... 2020 male early_neonatal malnourished                        251.0
                                                                                       not_malnourished                   2517.0
           diarrheal_diseases_to_susceptible_to_diarrheal_... 2020 male early_neonatal malnourished                        163.0
                                                                                       not_malnourished                   1608.0
           susceptible_to_measles_to_measles                  2020 male early_neonatal malnourished                          0.0
                                                                                       not_malnourished                      0.0
           measles_to_recovered_from_measles                  2020 male early_neonatal malnourished                          0.0
                                                                                       not_malnourished                      0.0
           susceptible_to_lower_respiratory_infections_to_... 2020 male early_neonatal malnourished                          1.0
                                                                                       not_malnourished                     37.0
           lower_respiratory_infections_to_susceptible_to_... 2020 male early_neonatal malnourished                         15.0
                                                                                       not_malnourished                    202.0
           susceptible_to_meningitis_to_meningitis            2020 male early_neonatal malnourished                          6.0
                                                                                       not_malnourished                     64.0
           meningitis_to_susceptible_to_meningitis            2020 male early_neonatal malnourished                          1.0
                                                                                       not_malnourished                     12.0
           susceptible_to_diarrheal_diseases_to_diarrheal_... 2020 male late_neonatal  malnourished                        700.0
                                                                                       not_malnourished                   7162.0
           diarrheal_diseases_to_susceptible_to_diarrheal_... 2020 male late_neonatal  malnourished                        681.0
                                                                                       not_malnourished                   7013.0